# -*- coding: utf-8 -*-
"""test_divisivel.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rk8vulnpZPR00ihA6Bp6AQ_nLlgZXiCV
"""

import pytest

def div(a,b):
  return a % b == 0

def test_div():
  assert div(7, 91) == False